# Generated by Django 4.1 on 2023-02-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.SmallIntegerField(max_length=90)),
                ('event_id', models.SmallIntegerField(max_length=90)),
                ('booked_date', models.DateField()),
                ('p_name', models.CharField(max_length=90)),
                ('p_email', models.CharField(max_length=90)),
                ('p_phone', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
