# Generated by Django 4.1 on 2023-02-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=90)),
                ('event_date', models.DateField()),
                ('org_email', models.CharField(max_length=90)),
                ('org_phone', models.BigIntegerField()),
                ('event_desc', models.TextField()),
                ('event_type', models.CharField(max_length=90)),
                ('event_loc', models.CharField(max_length=90)),
                ('event_status', models.CharField(max_length=90)),
                ('max_seats', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='book_id',
            field=models.BigIntegerField(max_length=90),
        ),
        migrations.AlterField(
            model_name='register',
            name='event_id',
            field=models.BigIntegerField(max_length=90),
        ),
    ]
